### ISSUE TITLE
miHoYoLogin.js里面最后的config是哪来的

### ISSUE THREAD

**Issue by ZM-J** [HDTianRu/TianRu-plugin#2]
rt，javascript小白

每次在miHoYoLoginHelp里面会报错

```
[MiaoYz][13:06:10.947][ERRO] ReferenceError: config is not defined
    at miHoYoLogin.miHoYoLoginHelp (file:///D:/code/Miao-Yunzai/plugins/TianRu-plugin/apps/miHoYoLogin.js:259:5)
    at PluginsLoader.deal (file:///D:/code/Miao-Yunzai/lib/plugins/loader.js:265:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

请问如何解决

**Comment by HDTianRu** [comment]
我的问题，复制的时候忘删掉config了，修了（
